server:
  port: 9102

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: order-service
#          predicates:
#            - "Path=/order/**"
#          filters:
#            - StripPrefix=1
#          uri: "http://amisno-order-service:8081"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://amisno-infra-eureka:9103/eureka/
