server:
  port: 9102

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://amisno-infra-eureka:9103/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'